weatherapp:
  target: dev
  outputs:
    dev:
      type: snowflake
      account:  IFNTRPR-AK19625
      user: GOOSE
      password: "{{ env_var('DBT_SNOWFLAKE_PASSWORD') }}"
      # authenticator: externalbrowser
      role: ACCOUNTADMIN
      warehouse: COMPUTE_WH
      database: WEATHER
      schema: CURATED
      threads: 4
